name: liin_lang
description: A simple functional programing language for creating automatization instructions like work with media files, text files and others
version: 0.5.1-nullsafety
repository: https://github.com/uslashvlad/liin_lang
publish_to: https://pub.dev
# homepage: https://nothing

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  expressions: ^0.2.0-nullsafety.1
  ansicolor: ^2.0.0-nullsafety.0
  path: ^1.8.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
